### PR TITLE
Some code cleanup, added fixed exposure points

### PR DESCRIPTION
**Pull request by Aypac**
Hi again,
I finally came around to using your library. Pretty neat! In order to understand the code better, I worked my way through it, did some PIP8 auto-formatting, added some PEP 484 type hints etc. Also I added many comments about my understanding of certain parts of code to (hopefully) make it easier for others to read.

Furthermore, I added some structures and an example of my own, requiring me to implement the PSF that we have been using. Finally, I added the possibility to add some points with a fixed dose (that are not being optimized). This helped me get better (and faster) results, especially when trying to fill larger areas.

I made sure, that everything remains backwards compatible. I checked that, by running the dimer_example.py and line_example.py - I got the same results as before.

Please let me know what you think and if you want me to change anything before a merge.

### CODE REVIEW

**Comment by sdickreuter** [comment]
Nice work! 
The idea with the fixed points is great, and is much better than using a variable centre point.
If you have some ideas to make the code easier or more flexible feel free to break compatibility, because this repo is mainly for new users and my colleagues use local copies.

**Comment by sdickreuter** [comment]
I also considered making a package out of the code, but I'm not sure if that would be beneficial.
Do you think that would make using the code easier ?

**Comment by Aypac** [comment]
Hi,
thank you for the encouraging words!
I have some more ideas, but not sure how much time I'll have to implement :) The first thing I would love to look into is symmetry constraints (i.e. two or more points should always have the same dose). That would again make the algorithm faster and should also improve the results overall - I believe even for all the examples out there right now. That, however, might proof to be quite a lot of work. I'll look into it later.

I was also considering to make it a package (that would make installing easy (`pip install git+url`) and also nicely resolve the dependencies). But more importantly, it would make it much easier to use this as part of another piece of software (i.e. some design software - I'm considering to use it to automatically correct certain small features (Josephson-Junctions) inside a larger design). If I am going to do that, it is very likely that I will make this a package first.

I'll make sure to keep sending pull requests as I go along, so that you can decide what you find beneficial for your repo.

**Comment by sdickreuter** [comment]
Time is always the problem :) Symmetry constraints would be neat, but as you said would require a lot of work ... There is however one advantage to not using symmetry, and that is that if the algorithm converges to a symmetric result by itself you can be sure that the formulation of your problem and the settings were perfectly solvable by the algorithm.
I did the package conversion, so that should make things easier :)
That sounds like a good use case, hopefully this will help you to make nice junctions, and improvements are always welcome!

**Pull request merged**
